version: '3.8'

services:
  society-management:
    image: society-management
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: prod
    volumes:
      - .:/usr/src/app/society-management
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    restart: always
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6370:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--requirepass", "wAGKORJRPu9cFBoUfkkXuBEI3NMTzlYB", "--appendonly", "yes" ]
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.2'
          memory: 256M
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
