version: '3.8'

services:
  society-management:
    image: society-management
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: prod
    volumes:
      - .:/usr/src/app/society-management
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: 256M
    restart: unless-stopped
    # healthcheck:
    #   test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:3000/api/health" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6370:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--requirepass", "wAGKORJRPu9cFBoUfkkXuBEI3NMTzlYB", "--appendonly", "yes" ]
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          cpus: '0.2'
          memory: 128M
    restart: unless-stopped
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # HTTP for initial Certbot verification
      - "443:443" # HTTPS for secure connections
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount your main nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - society-management
    restart: unless-stopped
    command: /bin/sh -c "until curl --silent --fail http://society-management:8080; do echo 'Waiting for society-management...'; sleep 2; done; exec nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
