version: '3.8'

services:
  society-management:
    image: society-management
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: prod
    volumes:
      - .:/usr/src/app/society-management
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: 256M
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6370:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--requirepass", "wAGKORJRPu9cFBoUfkkXuBEI3NMTzlYB", "--appendonly", "yes" ]
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          cpus: '0.2'
          memory: 128M
    restart: unless-stopped
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # HTTP for initial Certbot verification
      - "443:443" # HTTPS for secure connections
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount custom nginx config
      - /etc/letsencrypt:/etc/letsencrypt # SSL certificates location
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - society-management
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
